# Generated by Django 5.2 on 2025-05-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customuser_age_customuser_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
