# Generated by Django 5.2 on 2025-05-05 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_pcosprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='BMI',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PCOSPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('cycleType', models.CharField(choices=[('R', 'Regular'), ('I', 'Irregular')], max_length=1)),
                ('cycleLength', models.PositiveIntegerField()),
                ('marriedYears', models.PositiveIntegerField()),
                ('pregnant', models.PositiveIntegerField()),
                ('abortions', models.PositiveIntegerField()),
                ('risk_level', models.FloatField()),
                ('hormonal_imbalance', models.FloatField()),
                ('cycle_irregularity', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField()),
                ('MeanCycleLength', models.PositiveIntegerField(help_text='Average length of the menstrual cycle in days')),
                ('ReproductiveCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('BMI', models.FloatField(blank=True, null=True)),
                ('Weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start_date'],
            },
        ),
        migrations.DeleteModel(
            name='PCOSPrediction',
        ),
    ]
