# Generated by Django 5.2 on 2025-05-05 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_customuser_bmi_customuser_height_pcospredictionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow', models.PositiveSmallIntegerField(help_text='Flow intensity 1–5')),
                ('mood', models.CharField(max_length=20)),
                ('symptoms', models.JSONField(default=list, help_text="List of strings, e.g. ['Cramps','Bloating']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
