# Generated by Django 5.2 on 2025-05-05 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_dailyentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodlog',
            name='user',
        ),
        migrations.CreateModel(
            name='CycleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow', models.PositiveSmallIntegerField(default=0, help_text='1–5, or 0=no flow')),
                ('mood', models.CharField(blank=True, max_length=20)),
                ('symptoms', models.JSONField(default=list, help_text="e.g. ['Cramps','Bloating']")),
                ('is_period_start', models.BooleanField(default=False)),
                ('MeanCycleLength', models.PositiveIntegerField(blank=True, help_text='Avg cycle length on this start date', null=True)),
                ('ReproductiveCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('BMI', models.FloatField(blank=True, null=True)),
                ('Weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
        migrations.DeleteModel(
            name='PeriodLog',
        ),
    ]
