# Generated by Django 5.2 on 2025-05-05 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_periodlog_user_cycleentry_delete_dailyentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCOSDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pcos_detections/')),
                ('score', models.FloatField(help_text='Probability score from the detector model')),
                ('label', models.CharField(help_text="Predicted label, e.g. 'PCOS Detected' or 'No PCOS'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcos_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
